terraform {
  required_version = "~> 1.0.8"

  required_providers {
    google = {
      source = "hashicorp/google"
    }
    google-beta = {
      source = "hashicorp/google-beta"
    }
    helm = {
      source = "hashicorp/helm"
    }
    null = {
      source = "hashicorp/null"
    }
    kubernetes = {
      source = "hashicorp/kubernetes"
    }
    random = {
      source = "hashicorp/random"
    }
    local = {
      source = "hashicorp/local"
    }
    template = {
      source = "hashicorp/template"
    }
  }
}

provider "google" {
  project = var.project_id_dev
  region  = var.primary_region
  zone    = var.primary_zone
  // credentials json file path by default read from GOOGLE_APPLICATION_CREDENTIALS environment variable
}
provider "kubernetes" {
  // this kubeconfig file is generated by the kibeconfig tf module in gke.tf
  config_path    = "kubeconfig"
  config_context = "pals-kubernetes-context"
}

provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
}